# Generated by Django 5.1.7 on 2025-11-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hruser',
            options={'ordering': ['-updated_at'], 'verbose_name': '1.Tài khoản', 'verbose_name_plural': '1.Danh sách tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='userconfigs',
            options={'ordering': ['-updated_at'], 'verbose_name': '3.Cấu hình người dùng', 'verbose_name_plural': '3.Cấu hình người dùng'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': '2.Thông tin người dùng', 'verbose_name_plural': '2.Thông tin người dùng'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_fk', to='hr_pro.hruser'),
        ),
    ]
