# Generated by Django 5.1.7 on 2025-11-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0002_alter_hruser_options_alter_userconfigs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
