# Generated by Django 5.1.7 on 2025-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0003_userprofile_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timviec',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('normal', 'Người tìm việc'), ('company', 'Nhà tuyển dụng'), ('support', 'Hỗ trợ viên'), ('partner', 'Cộng tác viên'), ('admin', 'Quản trị viên')], default='normal', max_length=20),
        ),
    ]
