# Generated by Django 5.1.7 on 2025-11-13 02:31

import django.db.models.deletion
import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0004_userprofile_timviec_alter_userprofile_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baiviet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidung', models.TextField(blank=True, max_length=600, null=True)),
                ('lat_location', models.CharField(blank=True, max_length=20, null=True)),
                ('long_location', models.CharField(blank=True, max_length=20, null=True)),
                ('location_name', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binhluans', models.ManyToManyField(blank=True, related_name='binhluan_posts', to='hr_pro.hruser')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='hr_pro.hruser')),
                ('loadeds', models.ManyToManyField(blank=True, related_name='loaded_posts', to='hr_pro.hruser')),
                ('shares', models.ManyToManyField(blank=True, related_name='shared_posts', to='hr_pro.hruser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_pro.hruser')),
                ('vieweds', models.ManyToManyField(blank=True, related_name='viewd_posts', to='hr_pro.hruser')),
            ],
            options={
                'verbose_name': '4.Bài viết',
                'verbose_name_plural': '4.Bài viết',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnhBaiviet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/', validators=[hr_pro.models.validate_image_file])),
                ('file_name', models.CharField(blank=True, max_length=180, null=True)),
                ('file_type', models.CharField(blank=True, max_length=80, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baiviet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hr_pro.baiviet')),
            ],
            options={
                'verbose_name': '6.Ảnh bài viết',
                'verbose_name_plural': '6.Ảnh bài viết',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidung', models.CharField(blank=True, max_length=180, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baiviet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_pro.baiviet')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to='hr_pro.hruser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hr_pro.binhluan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_pro.hruser')),
            ],
            options={
                'verbose_name': '5.Bình luận',
                'verbose_name_plural': '5.Bình luận',
                'ordering': ['-updated_at'],
            },
        ),
    ]
