# Generated by Django 5.1.7 on 2025-11-13 03:02

import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0005_baiviet_anhbaiviet_binhluan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anhbaiviet',
            name='image',
            field=models.ImageField(upload_to=hr_pro.models.post_image_upload_path, validators=[hr_pro.models.validate_image_file]),
        ),
    ]
