# Generated by Django 5.1.7 on 2025-11-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0006_alter_anhbaiviet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binhluan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_pro.hruser'),
        ),
    ]
