# Generated by Django 5.1.7 on 2025-11-13 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0007_alter_binhluan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiviet',
            name='binhluans',
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_pro.hruser'),
        ),
    ]
