# Generated by Django 5.1.7 on 2025-11-13 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0008_remove_baiviet_binhluans_alter_baiviet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binhluan',
            name='baiviet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hr_pro.baiviet'),
        ),
    ]
