# Generated by Django 5.1.7 on 2025-11-14 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0009_alter_binhluan_baiviet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhgiaUngvienTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '9.Apply vị trí tuyển dụng',
                'verbose_name_plural': '9.Apply vị trí tuyển dụng',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='anhbaiviet',
            name='file_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='BaivietTuyendung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('tuyengap', models.BooleanField(default=False)),
                ('chinhthuc', models.BooleanField(default=True)),
                ('bophan', models.CharField(blank=True, max_length=100, null=True)),
                ('vitri', models.CharField(blank=True, max_length=100, null=True)),
                ('yeucau', models.TextField(blank=True, max_length=600, null=True)),
                ('quyenloi', models.TextField(blank=True, max_length=600, null=True)),
                ('noidungbosung', models.TextField(blank=True, max_length=600, null=True)),
                ('thuong', models.IntegerField(default=0)),
                ('dieukien_thuong', models.TextField(blank=True, max_length=300, null=True)),
                ('max_old', models.IntegerField(default=55)),
                ('min_old', models.IntegerField(default=18)),
                ('soluong', models.IntegerField(default=100)),
                ('ngayketthuc', models.DateField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='tuyendung_liked_posts', to='hr_pro.hruser')),
                ('loadeds', models.ManyToManyField(blank=True, related_name='tuyendung_loaded_posts', to='hr_pro.hruser')),
                ('shares', models.ManyToManyField(blank=True, related_name='tuyendung_shared_posts', to='hr_pro.hruser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_pro.hruser')),
                ('vieweds', models.ManyToManyField(blank=True, related_name='tuyendung_viewd_posts', to='hr_pro.hruser')),
            ],
            options={
                'verbose_name': '8.Tin tuyển dụng',
                'verbose_name_plural': '8.Tin tuyển dụng',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplyBaivietTuyendung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodienthoai', models.TextField(blank=True, max_length=15, null=True)),
                ('hovaten', models.TextField(blank=True, max_length=50, null=True)),
                ('noidungungtuyen', models.TextField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nguoigioithieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_gioithieu', to='hr_pro.hruser')),
                ('nguoiungtuyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_ungtuyen', to='hr_pro.hruser')),
                ('baiviet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.baiviettuyendung')),
            ],
            options={
                'verbose_name': '9.Apply vị trí tuyển dụng',
                'verbose_name_plural': '9.Apply vị trí tuyển dụng',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('hotline', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('address_details', models.JSONField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '6.Danh sách công ty',
                'verbose_name_plural': '6.Danh sách công ty',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.companylists'),
        ),
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ManyToManyField(blank=True, related_name='companies_admin', to='hr_pro.hruser')),
                ('companies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.companylists')),
                ('partner', models.ManyToManyField(blank=True, related_name='companies_partner', to='hr_pro.hruser')),
                ('staff', models.ManyToManyField(blank=True, related_name='companies_staff', to='hr_pro.hruser')),
                ('writer', models.ManyToManyField(blank=True, related_name='companies_writer', to='hr_pro.hruser')),
            ],
            options={
                'verbose_name': '7.Nhân sự công ty',
                'verbose_name_plural': '7.Nhân sự công ty',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DanhgiaUngvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ketqua', models.TextField(blank=True, choices=[('pass', 'Đỗ'), ('fail', 'Trượt'), ('wait', 'Chờ'), ('hold', 'Chưa đánh giá')], max_length=50, null=True)),
                ('ghichu', models.TextField(blank=True, max_length=200, null=True)),
                ('danhgia', models.TextField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baiviet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.applybaiviettuyendung')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.hruser')),
                ('tags', models.ManyToManyField(blank=True, to='hr_pro.danhgiaungvientags')),
            ],
            options={
                'verbose_name': '10. Đánh giá ứng viên',
                'verbose_name_plural': '10. Đánh giá ứng viên',
                'ordering': ['-updated_at'],
            },
        ),
    ]
