# Generated by Django 5.1.7 on 2025-11-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0010_danhgiaungvientags_alter_anhbaiviet_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhgiaungvientags',
            old_name='tagname',
            new_name='name',
        ),
    ]
