# Generated by Django 5.1.7 on 2025-11-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0011_rename_tagname_danhgiaungvientags_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaivietTuyendungTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '8.1 Tin tuyển dụng Tag',
                'verbose_name_plural': '8.1 Tin tuyển dụng Tag',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hr_pro.baiviettuyendungtags'),
        ),
    ]
