# Generated by Django 5.1.7 on 2025-11-14 08:38

import django.db.models.deletion
import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0012_baiviettuyendungtags_baiviettuyendung_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuCongNghiep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(upload_to=hr_pro.models.post_image_upload_path, validators=[hr_pro.models.validate_image_file])),
                ('mota', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '0. Khu công nghiệp',
                'verbose_name_plural': '0. Khu công nghiệp',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='khucongnhiep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.khucongnghiep'),
        ),
        migrations.AddField(
            model_name='companylists',
            name='khucongnhiep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.khucongnghiep'),
        ),
    ]
