# Generated by Django 5.1.7 on 2025-11-14 13:53

import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0013_khucongnghiep_baiviettuyendung_khucongnhiep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khucongnghiep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hr_pro.models.post_image_upload_path, validators=[hr_pro.models.validate_image_file]),
        ),
    ]
