# Generated by Django 5.1.7 on 2025-11-14 14:27

import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0014_alter_khucongnghiep_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anhbaiviet',
            options={'ordering': ['-created_at'], 'verbose_name': '0. Ảnh bài viết', 'verbose_name_plural': '0. Ảnh bài viết'},
        ),
        migrations.AddField(
            model_name='companylists',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=hr_pro.models.post_image_upload_path, validators=[hr_pro.models.validate_image_file]),
        ),
    ]
