# Generated by Django 5.1.7 on 2025-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0015_alter_anhbaiviet_options_companylists_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviettuyendung',
            name='ngayketthuc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companylists',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='comp_logos/'),
        ),
    ]
