# Generated by Django 5.1.7 on 2025-11-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0016_alter_baiviettuyendung_ngayketthuc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviettuyendung',
            name='mucluong',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
