# Generated by Django 5.1.7 on 2025-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0017_baiviettuyendung_mucluong'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='is_hightlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
