# Generated by Django 5.1.7 on 2025-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0018_baiviet_is_hightlight_baiviet_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylists',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
