# Generated by Django 5.1.7 on 2025-11-20 09:50

import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0019_companylists_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hr_pro.models.post_image_upload_path, validators=[hr_pro.models.validate_image_file])),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file_type', models.CharField(blank=True, max_length=80, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '6.0. Ảnh công ty',
                'verbose_name_plural': '6.0. Ảnh công ty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='companylists',
            name='hiring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companylists',
            name='max_tuoi',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='companylists',
            name='min_tuoi',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='companylists',
            name='mota',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='companylists',
            name='images',
            field=models.ManyToManyField(blank=True, to='hr_pro.companyimages'),
        ),
    ]
