# Generated by Django 5.1.7 on 2025-11-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0020_companyimages_companylists_hiring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baiviettuyendung',
            old_name='tuyengap',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='baiviettuyendung',
            old_name='dieukien_thuong',
            new_name='thuong_dieukien',
        ),
        migrations.RenameField(
            model_name='baiviettuyendung',
            old_name='bophan',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='baiviettuyendung',
            name='chinhthuc',
        ),
        migrations.RemoveField(
            model_name='baiviettuyendung',
            name='khucongnhiep',
        ),
        migrations.RemoveField(
            model_name='baiviettuyendung',
            name='mucluong',
        ),
        migrations.RemoveField(
            model_name='baiviettuyendung',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='baiviettuyendung',
            name='vitri',
        ),
        migrations.RemoveField(
            model_name='companylists',
            name='hiring',
        ),
        migrations.RemoveField(
            model_name='companylists',
            name='images',
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='calamviec',
            field=models.CharField(blank=True, choices=[('hc', 'Hành chính'), ('2ca', 'Ca ngày, đêm'), ('3ca', '3 ca'), ('lh', 'Linh hoạt')], default='2ca', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='chuyencan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='cuatu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='images',
            field=models.ManyToManyField(blank=True, to='hr_pro.companyimages'),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='loaihinh',
            field=models.CharField(blank=True, choices=[('tv', 'Thời vụ'), ('ct', 'Chính thức'), ('all', 'Thời vụ và chính thức')], default='all', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='luongcoban',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='luongtuan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='phongsach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='phucap',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='thuong_sotien',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baiviettuyendung',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baiviettuyendung',
            name='thuong',
            field=models.BooleanField(default=False),
        ),
    ]
