# Generated by Django 5.1.7 on 2025-11-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0021_rename_tuyengap_baiviettuyendung_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviettuyendung',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
