# Generated by Django 5.1.7 on 2025-11-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0022_baiviettuyendung_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviettuyendung',
            name='mucluong',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
