# Generated by Django 5.1.7 on 2025-11-22 08:39

import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0023_baiviettuyendung_mucluong'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaivietTuyenDungImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hr_pro.models.post_image_upload_path, validators=[hr_pro.models.validate_image_file])),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file_type', models.CharField(blank=True, max_length=80, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '8.1. Ảnh bải viết tuyển dụng',
                'verbose_name_plural': '8.1. Ảnh bải viết tuyển dụng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='baiviettuyendung',
            name='images',
            field=models.ManyToManyField(blank=True, to='hr_pro.baiviettuyendungimages'),
        ),
    ]
