# Generated by Django 5.1.7 on 2025-11-23 14:27

import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0024_baiviettuyendungimages_alter_baiviettuyendung_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviettuyendung',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hr_pro.baiviettuyendungtags'),
        ),
        migrations.AlterField(
            model_name='baiviettuyendungimages',
            name='image',
            field=models.ImageField(upload_to=hr_pro.models.post_tdimage_upload_path, validators=[hr_pro.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='khucongnghiep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hr_pro.models.post_cpimage_upload_path, validators=[hr_pro.models.validate_image_file]),
        ),
    ]
