# Generated by Django 5.1.7 on 2025-11-24 02:35

import django.db.models.deletion
import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0025_baiviettuyendung_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hr_pro.models.post_userimage_upload_path, validators=[hr_pro.models.validate_image_file])),
                ('album', models.CharField(blank=True, max_length=80, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file_type', models.CharField(blank=True, max_length=80, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.hruser')),
            ],
            options={
                'verbose_name': '8.1. Ảnh của người dùng',
                'verbose_name_plural': '8.1. Ảnh của người dùng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_pro.userimage'),
        ),
    ]
