# Generated by Django 5.1.7 on 2025-11-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0026_userimage_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
