# Generated by Django 5.1.7 on 2025-11-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0027_userprofile_cccd_alter_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invent_code',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
