# Generated by Django 5.1.7 on 2025-11-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0028_userprofile_invent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviettuyendung',
            name='view_count',
            field=models.BooleanField(default=0),
        ),
    ]
