# Generated by Django 5.1.7 on 2025-11-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0029_baiviettuyendung_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviettuyendung',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
