# Generated by Django 5.1.7 on 2025-11-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0030_alter_baiviettuyendung_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviettuyendung',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
