# Generated by Django 5.1.7 on 2025-12-17 07:50

import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0031_baiviettuyendung_share_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnhSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hr_pro.models.post_slice_upload_path, validators=[hr_pro.models.validate_image_file])),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file_type', models.CharField(blank=True, max_length=80, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('exprice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '10. Ảnh Slice',
                'verbose_name_plural': '10. Ảnh Slice',
                'ordering': ['-created_at'],
            },
        ),
    ]
