# Generated by Django 5.1.7 on 2025-12-17 09:37

import hr_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pro', '0032_anhslice'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviettuyendung',
            name='hotline',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='anhslice',
            name='image',
            field=models.ImageField(upload_to=hr_pro.models.post_slice_upload_path),
        ),
    ]
