# Generated by Django 5.1.7 on 2025-07-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('oauth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
