# Generated by Django 5.1.7 on 2025-08-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0003_alter_noteuser_oauth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotes',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='usernotes',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usernotes',
            name='sdt',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usernotes',
            name='sotien',
            field=models.IntegerField(default=0),
        ),
    ]
