# Generated by Django 5.1.7 on 2025-08-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0004_rename_title_usernotes_name_usernotes_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='note_type',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
