# Generated by Django 5.1.7 on 2025-08-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0005_usernotes_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='phanloai',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='in', max_length=12, null=True),
        ),
    ]
