# Generated by Django 5.1.7 on 2025-08-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0006_usernotes_phanloai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotes',
            old_name='pinned',
            new_name='ghim',
        ),
        migrations.RenameField(
            model_name='usernotes',
            old_name='content',
            new_name='noidung',
        ),
    ]
