# Generated by Django 5.1.7 on 2025-08-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0007_rename_pinned_usernotes_ghim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotes',
            old_name='shared_with',
            new_name='chiasecho',
        ),
        migrations.RenameField(
            model_name='usernotes',
            old_name='customer',
            new_name='khachhang',
        ),
        migrations.RenameField(
            model_name='usernotes',
            old_name='note_type',
            new_name='loai',
        ),
        migrations.RenameField(
            model_name='usernotes',
            old_name='name',
            new_name='tenghichu',
        ),
    ]
