# Generated by Django 5.1.7 on 2025-08-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0008_rename_shared_with_usernotes_chiasecho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='thoigian',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
