# Generated by Django 5.1.7 on 2025-09-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0009_usernotes_thoigian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotes',
            name='sdt',
        ),
        migrations.CreateModel(
            name='NoteCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(blank=True, max_length=100, null=True)),
                ('sodienthoai', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartnote.noteuser')),
            ],
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='khachhang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartnote.notecustomer'),
        ),
    ]
