# Generated by Django 5.1.7 on 2025-09-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0010_remove_usernotes_sdt_notecustomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecustomer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartnote.noteuser'),
        ),
    ]
