# Generated by Django 5.1.7 on 2025-09-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0012_notetype_alter_usernotes_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='trangthai',
            field=models.CharField(choices=[('not', 'not'), ('done', 'done')], default='not', max_length=12, null=True),
        ),
    ]
