# Generated by Django 5.1.7 on 2025-09-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0013_usernotes_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='dongia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usernotes',
            name='soluong',
            field=models.IntegerField(default=0),
        ),
    ]
