# Generated by Django 5.1.7 on 2025-09-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0013_usernotes_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='noidung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
