# Generated by Django 5.1.7 on 2025-09-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0014_alter_usernotes_noidung'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
