# Generated by Django 5.1.7 on 2025-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0015_userprofile_address_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isStore',
            field=models.BooleanField(default=False),
        ),
    ]
