# Generated by Django 5.1.7 on 2025-09-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0016_userprofile_isstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='store_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thongtinthem',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
