# Generated by Django 5.1.7 on 2025-09-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0014_usernotes_dongia_usernotes_soluong'),
        ('smartnote', '0017_remove_userprofile_address_remove_userprofile_phone_and_more'),
    ]

    operations = [
    ]
