# Generated by Django 5.1.7 on 2025-09-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0018_merge_20250922_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='dongia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='soluong',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='sotien',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
