# Generated by Django 5.1.7 on 2025-09-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnote', '0019_alter_usernotes_dongia_alter_usernotes_soluong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecustomer',
            name='ghim',
            field=models.BooleanField(default=False),
        ),
    ]
