# Generated by Django 5.1.7 on 2026-03-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zusers',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zusers',
            name='isdevelopment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zusers',
            name='isvalidated',
            field=models.BooleanField(default=False),
        ),
    ]
