# Generated by Django 5.1.7 on 2026-03-27 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0002_zusers_isadmin_zusers_isdevelopment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cardid', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('jobtitle', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='zusers',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zconnect.company'),
        ),
        migrations.CreateModel(
            name='RequestNoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='zconnect.company')),
            ],
        ),
        migrations.CreateModel(
            name='RequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('picture', models.FileField(blank=True, null=True, upload_to='note_pictures/')),
                ('content', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('processing_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='zconnect.zusers')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.company')),
                ('favorited', models.ManyToManyField(blank=True, related_name='favorite_notes', to='zconnect.zusers')),
                ('implement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementer', to='zconnect.zusers')),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_notes', to='zconnect.zusers')),
                ('pinned', models.ManyToManyField(blank=True, related_name='pinned_notes', to='zconnect.zusers')),
                ('viewed', models.ManyToManyField(blank=True, related_name='viewed_notes', to='zconnect.zusers')),
                ('categories', models.ManyToManyField(related_name='notes', to='zconnect.requestnotecategory')),
            ],
        ),
        migrations.CreateModel(
            name='RequestNoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.zusers')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='zconnect.requestnote')),
            ],
        ),
        migrations.CreateModel(
            name='RequestNoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.zusers')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='zconnect.requestnote')),
            ],
        ),
        migrations.AddField(
            model_name='zusers',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zconnect.zprofile'),
        ),
    ]
