# Generated by Django 5.1.7 on 2026-03-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0003_zprofile_zusers_company_requestnotecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestnote',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='note_pictures/'),
        ),
        migrations.AlterField(
            model_name='zprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
