# Generated by Django 5.1.7 on 2026-03-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0004_alter_requestnote_picture_alter_zprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zusers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zconnect.company'),
        ),
        migrations.AlterField(
            model_name='zusers',
            name='zaloid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
