# Generated by Django 5.1.7 on 2026-03-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0005_alter_zusers_company_alter_zusers_zaloid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hotline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
