# Generated by Django 5.1.7 on 2026-03-30 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0007_zusernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('vi', models.CharField(blank=True, max_length=250, null=True)),
                ('color', models.CharField(default='#ef4444', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('color', models.CharField(default='#ef4444', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IssueImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('vi', models.CharField(blank=True, max_length=250, null=True)),
                ('color', models.CharField(default='#ef4444', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IssueRickCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('color', models.CharField(default='#ef4444', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EHSIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('step', models.CharField(choices=[('created', 'created'), ('reviewed', 'reviewed'), ('processing', 'processing'), ('closing', 'closing'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('rejected', 'rejected')], default='created', max_length=100, null=True)),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=100, null=True)),
                ('private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehsissues', to='zconnect.zusers')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.company')),
                ('area', models.ManyToManyField(blank=True, to='zconnect.issuearea')),
                ('categories', models.ManyToManyField(blank=True, to='zconnect.issuecategories')),
                ('impacts', models.ManyToManyField(blank=True, to='zconnect.issueimpact')),
                ('rickcategories', models.ManyToManyField(blank=True, to='zconnect.issuerickcategories')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EHSImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ehs_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zconnect.ehsissue')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EHSIssueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.zusers')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='zconnect.ehsissue')),
            ],
        ),
    ]
