# Generated by Django 5.1.7 on 2026-03-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0008_issuearea_issuecategories_issueimpact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehsissue',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ehsissue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
