# Generated by Django 5.1.7 on 2026-03-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0009_ehsissue_suggestion_alter_ehsissue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnote',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
