# Generated by Django 5.1.7 on 2026-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0010_requestnote_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehsissue',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
