# Generated by Django 5.1.7 on 2026-03-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0012_ehsaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('isAnonymous', models.BooleanField(default=False)),
                ('isProcessed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.zusers')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.company')),
            ],
        ),
    ]
