# Generated by Django 5.1.7 on 2026-03-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0013_mailrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
