# Generated by Django 5.1.7 on 2026-03-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0014_mailrequest_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='QNARequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('isAnonymous', models.BooleanField(default=False)),
                ('isAnswered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_answers', to='zconnect.zusers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.zusers')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.company')),
            ],
        ),
    ]
