# Generated by Django 5.1.7 on 2026-03-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0015_qnarequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnarequest',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qnarequest',
            name='answer_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_answers', to='zconnect.zusers'),
        ),
        migrations.AlterField(
            model_name='qnarequest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zconnect.zusers'),
        ),
    ]
