# Generated by Django 5.1.7 on 2026-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0016_alter_qnarequest_answer_alter_qnarequest_answer_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehsissuehistory',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
