# Generated by Django 5.1.7 on 2026-03-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0017_ehsissuehistory_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='zusernotification',
            name='app',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zusernotification',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
