# Generated by Django 5.1.7 on 2026-04-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0019_requestlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogin',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zconnect.company'),
        ),
    ]
