# Generated by Django 5.1.7 on 2026-04-20 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0020_requestlogin_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBINSheetTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_date', models.CharField(max_length=255)),
                ('week', models.CharField(max_length=255)),
                ('weekday', models.CharField(max_length=255)),
                ('clock_in', models.CharField(max_length=255)),
                ('clock_out', models.CharField(max_length=255)),
                ('emp_code', models.CharField(max_length=255)),
                ('punch_id', models.CharField(max_length=255)),
                ('punch_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ehs_images/')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zconnect.zusers')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zconnect.company')),
            ],
        ),
    ]
