# Generated by Django 5.1.7 on 2026-04-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0021_fbinsheettime_companynews'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbinsheettime',
            name='record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbinsheettime',
            name='att_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbinsheettime',
            name='clock_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbinsheettime',
            name='clock_out',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbinsheettime',
            name='emp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbinsheettime',
            name='punch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbinsheettime',
            name='punch_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbinsheettime',
            name='week',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbinsheettime',
            name='weekday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
