# Generated by Django 5.1.7 on 2025-05-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieclamvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('candidate', 'Người tìm việc'), ('employer', 'Nhà tuyển dụng')], default='candidate', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobs_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='vieclamvp.jobsuser')),
            ],
        ),
    ]
