# Generated by Django 5.1.7 on 2025-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0003_userplan_userconfigs_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfigs',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
