# Generated by Django 5.1.7 on 2025-07-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0006_users_last_login_alter_userprofile_user_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfigs',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
