# Generated by Django 5.1.7 on 2025-08-01 03:21

import django.db.models.deletion
import vieZ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0007_alter_userconfigs_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='userconfigs',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='userfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='userplan',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='UserApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('app_id', models.CharField(default=vieZ.models.generate_app_id, max_length=50, unique=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieZ.appcategorys')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vieZ.users')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
