# Generated by Django 5.1.7 on 2025-08-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0008_appcategorys_alter_userconfigs_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapps',
            old_name='app_name',
            new_name='name',
        ),
    ]
