# Generated by Django 5.1.7 on 2025-08-01 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0009_rename_app_name_userapps_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapps',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userapps',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userapps',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserAppsConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('configs', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.userapps')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
