# Generated by Django 5.1.7 on 2025-08-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0010_userapps_is_active_userapps_is_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappsconfigs',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
