# Generated by Django 5.1.7 on 2025-08-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0011_userappsconfigs_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapps',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.users'),
        ),
    ]
