# Generated by Django 5.1.7 on 2025-08-04 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0012_alter_userapps_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ProductsCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.users')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=225)),
                ('descriptions', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=False)),
                ('giaban', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieZ.userfile')),
                ('danhmuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieZ.productscategorys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.users')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
