# Generated by Django 5.1.7 on 2025-08-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0015_usernewsctl_usernews_userstore_storemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemember',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
