# Generated by Django 5.1.7 on 2025-08-13 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0018_remove_usernewsctl_user_storenewsctl_storenews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCollabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('img_base64', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.userstore')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
