# Generated by Django 5.1.7 on 2025-08-13 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0019_storecollabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='preview_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstore',
            name='store_hotline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userstore',
            name='store_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StoreProductsCtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.userstore')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('short', models.CharField(blank=True, max_length=225, null=True)),
                ('img_base64', models.TextField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.userstore')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.storeproductsctl')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
