# Generated by Django 5.1.7 on 2025-08-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0020_userstore_preview_img_userstore_store_hotline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storenews',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
