# Generated by Django 5.1.7 on 2025-08-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0021_alter_storenews_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='storenews',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
