# Generated by Django 5.1.7 on 2025-08-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0023_storeproducts_min_unit_storeproducts_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.storemember'),
        ),
    ]
