# Generated by Django 5.1.7 on 2025-08-14 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0024_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieZ.storemember'),
        ),
    ]
