# Generated by Django 5.1.7 on 2025-08-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0025_alter_orderhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='descriptions',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
