# Generated by Django 5.1.7 on 2025-08-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0027_alter_userproducts_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
