# Generated by Django 5.1.7 on 2025-08-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0028_alter_storeproducts_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemember',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StoreFeedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.storemember')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.userstore')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
