# Generated by Django 5.1.7 on 2025-08-15 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0029_storemember_avatar_storefeedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.storemember')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.storeproducts')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
