# Generated by Django 5.1.7 on 2025-08-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0030_membercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
