# Generated by Django 5.1.7 on 2025-08-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0031_membercart_is_ordered_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
        ),
    ]
