# Generated by Django 5.1.7 on 2025-08-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0032_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
