# Generated by Django 5.1.7 on 2025-08-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0033_alter_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefeedbacks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
