# Generated by Django 5.1.7 on 2025-08-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0034_alter_storefeedbacks_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefeedbacks',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vieZ.storemember'),
        ),
        migrations.AlterField(
            model_name='storefeedbacks',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vieZ.userstore'),
        ),
    ]
