# Generated by Django 5.1.7 on 2025-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0035_alter_storefeedbacks_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='store_collabs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
