# Generated by Django 5.1.7 on 2025-08-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0036_userstore_store_collabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
