# Generated by Django 5.1.7 on 2025-08-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0037_alter_userfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
