# Generated by Django 5.1.7 on 2025-08-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0039_alter_userfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproducts',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
