# Generated by Django 5.1.7 on 2025-08-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0040_storeproducts_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='max_store',
            field=models.IntegerField(default=1),
        ),
    ]
