# Generated by Django 5.1.7 on 2025-08-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0041_userplan_max_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproducts',
            name='category',
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='storeproducts',
            name='category',
            field=models.ManyToManyField(blank=True, to='vieZ.storeproductsctl'),
        ),
    ]
