# Generated by Django 5.1.7 on 2025-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0042_remove_storeproducts_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='vieZ.storeproductsctl'),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
