# Generated by Django 5.1.7 on 2025-08-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0043_alter_storeproducts_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproducts',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
