# Generated by Django 5.1.7 on 2025-08-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0044_storeproducts_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproducts',
            name='sale',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
