# Generated by Django 5.1.7 on 2025-08-29 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0045_storeproducts_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcategorys',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='membercart',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productscategorys',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storecollabs',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storefeedbacks',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storemember',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storenews',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storenewsctl',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storeproducts',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storeproductsctl',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storeslides',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userapps',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userappsconfigs',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userconfigs',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userplan',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userproducts',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userproductstype',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userstore',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='storeproducts',
            name='sale',
        ),
        migrations.CreateModel(
            name='StoreSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('percent', 'Phần trăm'), ('price', 'Giá')], default='price', max_length=10)),
                ('percent', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('descriptions', models.TextField(blank=True, max_length=5000, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, null=True, to='vieZ.storeproducts')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieZ.userstore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
