# Generated by Django 5.1.7 on 2025-09-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0046_alter_appcategorys_options_alter_membercart_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_base64',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='category',
            field=models.ManyToManyField(null=True, to='vieZ.storeproductsctl'),
        ),
        migrations.AlterField(
            model_name='storesales',
            name='products',
            field=models.ManyToManyField(blank=True, to='vieZ.storeproducts'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
