# Generated by Django 5.1.7 on 2025-09-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0047_remove_userprofile_avatar_base64_userprofile_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='max_warehouse',
            field=models.IntegerField(default=1),
        ),
    ]
