# Generated by Django 5.1.7 on 2025-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0048_userplan_max_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_number',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
