# Generated by Django 5.1.7 on 2025-09-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0049_userprofile_bank_code_userprofile_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
