# Generated by Django 5.1.7 on 2025-09-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0050_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
