# Generated by Django 5.1.7 on 2025-09-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieZ', '0051_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
