# Generated by Django 5.1.7 on 2025-05-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0003_lastcheckgroup_zalouserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='last_have_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
