# Generated by Django 5.1.7 on 2025-05-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0004_usergroup_last_have_message_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveitem',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('disbursed', 'Đã giải ngân'), ('complete', 'Hoàn thành'), ('cancel', 'Hủy'), ('reject', 'Từ chối')], default='pending', max_length=100, null=True),
        ),
    ]
