# Generated by Django 5.1.7 on 2025-05-07 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0005_alter_approveitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvetype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pheduyet_zalo.usergroup'),
        ),
    ]
