# Generated by Django 5.1.7 on 2025-05-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0006_approvetype_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvetype',
            name='amount_approver',
            field=models.ManyToManyField(blank=True, related_name='type_amount_approver_member', to='pheduyet_zalo.zalouser'),
        ),
        migrations.AddField(
            model_name='approvetype',
            name='payment_approver',
            field=models.ManyToManyField(blank=True, related_name='type_payment_approver_member', to='pheduyet_zalo.zalouser'),
        ),
    ]
