# Generated by Django 5.1.7 on 2025-05-07 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0007_approvetype_amount_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveitemrecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pheduyet_zalo.approveitem'),
        ),
    ]
