# Generated by Django 5.1.7 on 2025-05-07 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0009_approveitemmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approveitemmessage',
            old_name='comment',
            new_name='message',
        ),
        migrations.CreateModel(
            name='LastCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_check', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pheduyet_zalo.approveitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pheduyet_zalo.zalouser')),
            ],
        ),
    ]
