# Generated by Django 5.1.7 on 2025-05-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0010_rename_comment_approveitemmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveitem',
            name='last_have_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
