# Generated by Django 5.1.7 on 2025-05-07 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0011_approveitem_last_have_message_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approveitem',
            options={'ordering': ['-last_have_message_at']},
        ),
        migrations.AlterModelOptions(
            name='approveitemmessage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='approveitemrecord',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='approvetype',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='lastcheckgroup',
            options={'ordering': ['-last_check']},
        ),
        migrations.AlterModelOptions(
            name='lastcheckitem',
            options={'ordering': ['-last_check']},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['-id'], 'verbose_name': 'Group approver', 'verbose_name_plural': 'Group approver'},
        ),
        migrations.CreateModel(
            name='ApproveItemEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('like', 'Thích'), ('tym', 'Thả tim'), ('haha', 'Haha'), ('sad', 'Buồn'), ('vl', 'Vler'), ('wow', 'Ồ'), ('angry', 'Dỗi')], default='like', max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pheduyet_zalo.approveitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pheduyet_zalo.zalouser')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
