# Generated by Django 5.1.7 on 2025-05-07 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheduyet_zalo', '0012_alter_approveitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pheduyet_zalo.usergroup')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserGroupRecord_target', to='pheduyet_zalo.zalouser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pheduyet_zalo.zalouser')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
