# Generated by Django 5.1.7 on 2025-03-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
