# Generated by Django 5.1.7 on 2025-03-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
