# Generated by Django 5.1.7 on 2025-03-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companystaffhistoryaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companyuser'),
        ),
        migrations.AlterField(
            model_name='companystaffhistory',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companyuser'),
        ),
    ]
