# Generated by Django 5.1.7 on 2025-03-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companystaff_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companystaff',
            old_name='name',
            new_name='cardID',
        ),
        migrations.AlterUniqueTogether(
            name='companystaff',
            unique_together={('company', 'cardID')},
        ),
    ]
