# Generated by Django 5.1.7 on 2025-03-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_miniapp_miniapppricing_miniappfunction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniapp',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='miniappfunction',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
