# Generated by Django 5.0.6 on 2025-04-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_appchatroom_chatmessage_miniappchatstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appchatroom',
            name='last_have_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
