# Generated by Django 5.0.6 on 2025-04-02 03:36

import company.models.miniapp
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_appchatroom_last_have_message_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appchatroom',
            options={'ordering': ['-last_have_message_at']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='appchatroom',
            name='members_add_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appchatroom',
            name='members_change_avatar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appchatroom',
            name='members_change_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appchatroom',
            name='members_remove_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=company.models.miniapp.chat_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='mention_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to='company.companystaff'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='company.chatmessage'),
        ),
        migrations.AlterField(
            model_name='appchatroom',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='appchatroom',
            name='members',
            field=models.ManyToManyField(to='company.companystaff'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='company.companystaff'),
        ),
        migrations.AlterField(
            model_name='miniappchatstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_status', to='company.companystaff'),
        ),
        migrations.CreateModel(
            name='ChatRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='company.appchatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_memberships', to='company.companystaff')),
            ],
        ),
        migrations.CreateModel(
            name='ChatDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_dates', to='company.appchatroom')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('room', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MiniAppConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('members_list', models.ManyToManyField(to='company.companystaff')),
                ('mini_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.miniapp')),
            ],
            options={
                'unique_together': {('mini_app', 'company')},
            },
        ),
    ]
