# Generated by Django 5.0.6 on 2025-04-02 03:41

import company.models.miniapp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_appchatroom_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=company.models.miniapp.chat_attachment_upload_path, validators=[company.models.miniapp.ChatMessage.validate_attachment_file_type]),
        ),
    ]
