# Generated by Django 5.0.6 on 2025-04-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_chatmessage_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiniAppChatStatus',
            new_name='AppChatStatus',
        ),
    ]
