# Generated by Django 5.1.7 on 2025-04-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_chatmessage_socket_sended'),
    ]

    operations = [
        migrations.AddField(
            model_name='appchatroom',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
