# Generated by Django 5.1.7 on 2025-04-06 17:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_appchatroom_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('hotline', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('staffs', models.ManyToManyField(blank=True, related_name='customers', to='company.companystaff')),
            ],
            options={
                'verbose_name': 'Company Customers',
                'verbose_name_plural': 'Company Customers',
                'ordering': ['-id'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompanySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('hotline', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Company Suppliers',
                'verbose_name_plural': 'Company Suppliers',
                'ordering': ['-id'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('hotline', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Company Vendors',
                'verbose_name_plural': 'Company Vendors',
                'ordering': ['-id'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhanvien', models.CharField(blank=True, max_length=200, null=True)),
                ('sdt', models.CharField(blank=True, max_length=15, null=True)),
                ('ho_ten', models.CharField(blank=True, max_length=200, null=True)),
                ('gioi_tinh', models.CharField(blank=True, max_length=200, null=True)),
                ('ten_goc', models.CharField(blank=True, max_length=200, null=True)),
                ('so_cccd', models.CharField(blank=True, max_length=200, null=True)),
                ('ngaysinh', models.DateField(blank=True, null=True)),
                ('diachi', models.CharField(blank=True, max_length=200, null=True)),
                ('quequan', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('cccd_front', models.TextField(blank=True, null=True)),
                ('cccd_back', models.TextField(blank=True, null=True)),
                ('trangthai', models.CharField(blank=True, max_length=200, null=True)),
                ('nganhang', models.CharField(blank=True, max_length=200, null=True)),
                ('so_taikhoan', models.CharField(blank=True, max_length=200, null=True)),
                ('chu_taikhoan', models.CharField(blank=True, max_length=200, null=True)),
                ('ghichu_taikhoan', models.CharField(blank=True, max_length=200, null=True)),
                ('ghichu', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('congty_danglam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companycustomer')),
                ('nguoibaocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyOP_nguoibaocao', to='company.companystaff')),
                ('nguoituyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyOP_nguoituyen', to='company.companystaff')),
                ('nhachinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companysupplier')),
                ('nhacungcap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companyvendor')),
            ],
            options={
                'verbose_name': 'Company Operators',
                'verbose_name_plural': 'Company Operators',
                'ordering': ['-id'],
                'unique_together': {('company', 'ma_nhanvien')},
            },
        ),
        migrations.CreateModel(
            name='OperatorUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companystaff')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='company.companyoperator')),
            ],
            options={
                'verbose_name': 'Company Operator History',
                'verbose_name_plural': 'Company Operator Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorWorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_cccd', models.CharField(blank=True, max_length=200, null=True)),
                ('anh_cccd_front', models.TextField(blank=True, null=True)),
                ('anh_cccd_back', models.TextField(blank=True, null=True)),
                ('ma_nhanvien', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_histories', to='company.companycustomer')),
                ('nguoituyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyHIS_nguoituyen', to='company.companystaff')),
                ('noihopdong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_histories', to='company.operatorworkhistory')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='company.companyoperator')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_histories', to='company.companysupplier')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_histories', to='company.companyvendor')),
            ],
            options={
                'verbose_name': 'Operator History',
                'verbose_name_plural': 'Operator Histories',
                'ordering': ['-id'],
            },
        ),
    ]
