# Generated by Django 5.1.7 on 2025-04-10 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_companycustomer_companysupplier_companyvendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_company_level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permission Type',
                'verbose_name_plural': 'Permission Types',
            },
        ),
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permission Type Target',
                'verbose_name_plural': 'Permission Types Target',
            },
        ),
        migrations.CreateModel(
            name='CompanyStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('avatar_base64', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='company.companystaff')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicable_departments', models.ManyToManyField(blank=True, related_name='company_permissions', to='company.companydepartment')),
                ('applicable_positions', models.ManyToManyField(blank=True, related_name='company_permissions', to='company.companypossition')),
                ('applicable_staff', models.ManyToManyField(blank=True, related_name='company_permissions', to='company.companystaff')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permissions', to='company.companystaff')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='company.company')),
                ('excluded_departments', models.ManyToManyField(blank=True, related_name='excluded_permissions', to='company.companydepartment')),
                ('excluded_staff', models.ManyToManyField(blank=True, related_name='excluded_permissions', to='company.companystaff')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to='company.permission')),
                ('permission_types', models.ManyToManyField(blank=True, related_name='company_permissions', to='company.permissiontype')),
                ('target_types', models.ManyToManyField(blank=True, related_name='company_permissions', to='company.targettype')),
            ],
            options={
                'verbose_name': 'Permission at Company',
                'verbose_name_plural': 'Permissions at Company',
                'unique_together': {('company', 'permission')},
            },
        ),
    ]
