# Generated by Django 5.1.7 on 2025-04-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_permission_permissiontype_targettype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaffprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
