# Generated by Django 5.1.7 on 2025-04-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_advancereasontype_advancerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companystaff'),
        ),
    ]
