# Generated by Django 5.1.7 on 2025-04-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_companystaff_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaffprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companystaffprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companystaffprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
