# Generated by Django 5.1.7 on 2025-04-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_alter_companystaffprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='operatorCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
