# Generated by Django 5.1.7 on 2025-04-12 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_company_operatorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoperator',
            name='ngay_phongvan',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 13), null=True),
        ),
    ]
