# Generated by Django 5.0.6 on 2025-04-15 09:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_companyoperator_ngay_phongvan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyoperator',
            name='ngay_phongvan',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 15), null=True),
        ),
        migrations.CreateModel(
            name='LastCheckAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=100)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companystaff')),
            ],
        ),
    ]
