# Generated by Django 5.0.6 on 2025-04-16 01:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_alter_companyoperator_ngay_phongvan_lastcheckapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyoperator',
            name='ngay_phongvan',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
