# Generated by Django 5.0.6 on 2025-04-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_alter_companyoperator_ngay_phongvan'),
    ]

    operations = [
        migrations.AddField(
            model_name='appchatroom',
            name='admins',
            field=models.ManyToManyField(related_name='appchatroom', to='company.companystaff'),
        ),
        migrations.AlterField(
            model_name='appchatroom',
            name='members',
            field=models.ManyToManyField(related_name='appchatroom_members', to='company.companystaff'),
        ),
    ]
