# Generated by Django 5.0.6 on 2025-04-16 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_appchatroom_admins_alter_appchatroom_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='appchatroom',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appchatroom_host', to='company.companystaff'),
        ),
        migrations.AlterField(
            model_name='appchatroom',
            name='admins',
            field=models.ManyToManyField(related_name='appchatroom_admins', to='company.companystaff'),
        ),
    ]
