# Generated by Django 5.0.6 on 2025-04-17 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_appchatroom_host_alter_appchatroom_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ghim_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghim_messages', to='company.companystaff'),
        ),
    ]
