# Generated by Django 5.0.6 on 2025-04-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_chatmessage_ghim_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='isAction',
            field=models.BooleanField(default=False),
        ),
    ]
