# Generated by Django 5.1.7 on 2025-04-23 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_chatmessage_isaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyoperator',
            name='nhachinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyOP_nhachinh', to='company.companyvendor'),
        ),
        migrations.RemoveField(
            model_name='operatorworkhistory',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='companyoperator',
            name='nhacungcap',
        ),
        migrations.AddField(
            model_name='companyoperator',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyOP_vendor', to='company.companyvendor'),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='isSystem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='operatorworkhistory',
            name='nhachinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_nhachinh', to='company.companyvendor'),
        ),
        migrations.AlterField(
            model_name='operatorworkhistory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_vendor', to='company.companyvendor'),
        ),
        migrations.DeleteModel(
            name='CompanySupplier',
        ),
    ]
