# Generated by Django 5.1.7 on 2025-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_alter_companyoperator_nhachinh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='isSystem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
