# Generated by Django 5.1.7 on 2025-04-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_companystaff_issystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='managerCustomer',
            field=models.ManyToManyField(blank=True, to='company.companycustomer'),
        ),
    ]
