# Generated by Django 5.1.7 on 2025-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_companystaff_managercustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaffprofile',
            name='chu_taikhoan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companystaffprofile',
            name='nganhang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companystaffprofile',
            name='so_taikhoan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
