# Generated by Django 5.1.7 on 2025-05-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_alter_advancerequest_reason_keepsalaryrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycustomer',
            name='staffs',
        ),
    ]
