# Generated by Django 5.1.7 on 2025-05-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_remove_companycustomer_staffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystaff',
            name='managerCustomer',
        ),
        migrations.RemoveField(
            model_name='companystaff',
            name='socket_id',
        ),
    ]
