# Generated by Django 5.1.7 on 2025-05-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_remove_companystaff_managercustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='managerCustomer',
            field=models.ManyToManyField(blank=True, to='company.companycustomer'),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='socket_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
