# Generated by Django 5.1.7 on 2025-05-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_companystaff_managercustomer_companystaff_socket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaffprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companystaffprofile',
            name='zalo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
