# Generated by Django 5.1.7 on 2025-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_delete_keepsalaryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorworkhistory',
            name='vitri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
