# Generated by Django 5.1.7 on 2025-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_operatorworkhistory_vitri'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorworkhistory',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='payment_status',
            field=models.CharField(choices=[('not', 'Chưa giải ngân'), ('done', 'Đã giải ngân')], default='not', max_length=10),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='retrieve_status',
            field=models.CharField(choices=[('not', 'Chưa thu hồi'), ('done', 'Đã thu hồi')], default='not', max_length=15),
        ),
    ]
