# Generated by Django 5.1.7 on 2025-05-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_operatorworkhistory_ho_ten_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyoperator',
            unique_together={('so_cccd', 'company', 'ma_nhanvien')},
        ),
    ]
