# Generated by Django 5.1.7 on 2025-05-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0045_alter_companyoperator_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyoperator',
            unique_together={('so_cccd', 'nhachinh', 'company', 'ma_nhanvien')},
        ),
    ]
