# Generated by Django 5.1.7 on 2025-05-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_alter_companyoperator_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyoperator',
            unique_together={('company', 'ma_nhanvien'), ('so_cccd', 'nhachinh')},
        ),
    ]
