# Generated by Django 5.1.7 on 2025-05-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_alter_companyoperator_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorworkhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatorworkhistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
