# Generated by Django 5.1.7 on 2025-05-28 07:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_alter_companyoperator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_can_approve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('staff_can_approve', models.ManyToManyField(blank=True, to='company.companystaff')),
            ],
            options={
                'verbose_name': 'Company Staff Action History Functions',
                'verbose_name_plural': 'Company Staff Action History Functions',
                'ordering': ['-id'],
            },
        ),
    ]
