# Generated by Django 5.1.7 on 2025-05-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0050_companyconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfig',
            options={'ordering': ['-id'], 'verbose_name': 'Company Configurations', 'verbose_name_plural': 'Company Configurations'},
        ),
    ]
