# Generated by Django 5.1.7 on 2025-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_alter_companyconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='admin_can_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='staff_can_payout',
            field=models.ManyToManyField(blank=True, related_name='list_can_payout', to='company.companystaff'),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='staff_can_approve',
            field=models.ManyToManyField(blank=True, related_name='list_can_approve', to='company.companystaff'),
        ),
    ]
