# Generated by Django 5.1.7 on 2025-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0053_companyconfig_approve_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancetype',
            name='need_retrive',
            field=models.BooleanField(default=False),
        ),
    ]
