# Generated by Django 5.1.7 on 2025-05-30 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0054_advancetype_need_retrive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyvendor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companyvendor',
            name='subname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='companyvendor',
            unique_together={('company', 'name', 'subname')},
        ),
        migrations.CreateModel(
            name='Company_Salary_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_action', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_action_target', models.IntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('shortname', models.CharField(blank=True, max_length=200, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_salary_type')),
                ('parent_action_target_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_type_target', to='company.company_salary_type')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCustomer_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=200, null=True)),
                ('input_field', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('hotline', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companycustomer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
