# Generated by Django 5.1.7 on 2025-05-30 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0055_alter_companyvendor_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycustomer_salary',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='companycustomer_salary',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companycustomer_salary',
            name='hotline',
        ),
        migrations.RemoveField(
            model_name='companycustomer_salary',
            name='input_field',
        ),
        migrations.RemoveField(
            model_name='companycustomer_salary',
            name='name',
        ),
        migrations.RemoveField(
            model_name='companycustomer_salary',
            name='website',
        ),
        migrations.AddField(
            model_name='companycustomer_salary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='companycustomer_salary',
            name='dongia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companycustomer_salary',
            name='ngayapdung',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companycustomer_salary',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companystaff'),
        ),
        migrations.AlterField(
            model_name='company_salary_type',
            name='parent_action_target',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='companycustomer_salary',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companycustomer'),
        ),
        migrations.CreateModel(
            name='Company_Hour_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('heso', models.IntegerField(blank=True, default=100, null=True)),
                ('shortname', models.CharField(blank=True, max_length=200, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyOperator_workHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaylamviec', models.DateField()),
                ('is_single', models.BooleanField(default=True)),
                ('denngay', models.DateField(blank=True, null=True)),
                ('heso', models.FloatField(blank=True, default=0, null=True)),
                ('sogio', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyoperator')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companystaff')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
