# Generated by Django 5.1.7 on 2025-06-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0056_remove_companycustomer_salary_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoperator',
            name='import_raw',
            field=models.JSONField(blank=True, max_length=9999, null=True),
        ),
    ]
