# Generated by Django 5.1.7 on 2025-06-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0058_companyvendor_is_sub_companyvendor_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereasontype',
            name='typename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='advancetype',
            name='typecode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='advancereasontype',
            unique_together={('company', 'typename')},
        ),
        migrations.AlterUniqueTogether(
            name='advancetype',
            unique_together={('company', 'typecode')},
        ),
    ]
