# Generated by Django 5.1.7 on 2025-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_alter_advancereasontype_typename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='approve_admin',
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='admin_can_update_op_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='admin_can_update_op_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='staff_approve_admin',
            field=models.ManyToManyField(blank=True, related_name='staff_approve_admin', to='company.companystaff'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='staff_can_approve_and_payout',
            field=models.ManyToManyField(blank=True, related_name='staff_can_approve_and_payout', to='company.companystaff'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='staff_can_update_op_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='staff_can_update_op_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='staffs_can_update_op_info',
            field=models.ManyToManyField(blank=True, related_name='staff_can_update_op_info', to='company.companystaff'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='staffs_can_update_op_work',
            field=models.ManyToManyField(blank=True, related_name='staff_can_update_op_work', to='company.companystaff'),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='staff_can_approve',
            field=models.ManyToManyField(blank=True, related_name='staff_can_approve', to='company.companystaff'),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='staff_can_payout',
            field=models.ManyToManyField(blank=True, related_name='staff_can_payout', to='company.companystaff'),
        ),
    ]
