# Generated by Django 5.1.7 on 2025-06-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_remove_companyconfig_approve_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='staff_can_approve',
        ),
    ]
