# Generated by Django 5.1.7 on 2025-06-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0062_companyconfig_staff_can_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='staff_can_approve',
        ),
    ]
