# Generated by Django 5.1.7 on 2025-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0063_remove_companyconfig_staff_can_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='staff_can_approve',
            field=models.ManyToManyField(blank=True, related_name='staff_can_approve', to='company.companystaff'),
        ),
    ]
