# Generated by Django 5.1.7 on 2025-06-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0064_companyconfig_staff_can_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='staff_approve_admin',
        ),
    ]
