# Generated by Django 5.1.7 on 2025-06-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0065_remove_companyconfig_staff_approve_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='staff_approve_admin',
            field=models.ManyToManyField(blank=True, related_name='staff_approve_admin', to='company.companystaff'),
        ),
    ]
