# Generated by Django 5.1.7 on 2025-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0066_companyconfig_staff_approve_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
