# Generated by Django 5.1.7 on 2025-07-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0068_contract_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoperator',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
