# Generated by Django 5.1.7 on 2025-07-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0069_companyoperator_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='baoung_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='baoung_active_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='baoung_active_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='baoung_active_time',
            field=models.BooleanField(default=False),
        ),
    ]
