# Generated by Django 5.1.7 on 2025-07-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0070_companyconfig_baoung_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='approve_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='editop_active',
            field=models.BooleanField(default=True),
        ),
    ]
