# Generated by Django 5.1.7 on 2025-07-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0071_companyconfig_approve_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='editopwork_active',
            field=models.BooleanField(default=True),
        ),
    ]
