# Generated by Django 5.1.7 on 2025-07-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0072_companyconfig_editopwork_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='baoung_active_end',
        ),
        migrations.RemoveField(
            model_name='companyconfig',
            name='baoung_active_start',
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='baoung_active_date',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='baoung_active_type',
            field=models.CharField(blank=True, default='week', max_length=10, null=True),
        ),
    ]
