# Generated by Django 5.1.7 on 2025-07-11 08:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0073_remove_companyconfig_baoung_active_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Tiêu đề', max_length=220, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Company Books',
                'verbose_name_plural': 'Company Books',
                'ordering': ['-id'],
            },
        ),
    ]
