# Generated by Django 5.1.7 on 2025-07-11 08:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0074_companybook'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='Tiêu đề', max_length=220, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companybook')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companystaff')),
            ],
            options={
                'verbose_name': 'Company Books Historys',
                'verbose_name_plural': 'Company Books Historys',
                'ordering': ['-id'],
            },
        ),
    ]
