# Generated by Django 5.1.7 on 2025-07-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0075_companybookhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybook',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companystaff'),
        ),
    ]
