# Generated by Django 5.1.7 on 2025-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0076_companybook_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybookhistory',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companybookhistory',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
