# Generated by Django 5.1.7 on 2025-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0077_companybookhistory_note_companybookhistory_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybookhistory',
            name='diff_text',
            field=models.TextField(blank=True),
        ),
    ]
