# Generated by Django 5.1.7 on 2025-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0078_companybookhistory_diff_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybookhistory',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
