# Generated by Django 5.1.7 on 2025-09-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0079_alter_companybookhistory_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('alert', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('loop', models.BooleanField(default=False)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('alert_day', models.JSONField(blank=True, null=True)),
                ('alert_time', models.TimeField()),
                ('repeat_time', models.IntegerField(default=0)),
                ('repeat_range', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='company.companystaff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
