# Generated by Django 5.1.7 on 2025-09-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0080_companystaffnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaffnote',
            name='alert_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
