# Generated by Django 5.1.7 on 2025-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0081_alter_companystaffnote_alert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaffnote',
            name='repeat_time',
            field=models.IntegerField(default=5),
        ),
    ]
