# Generated by Django 5.1.7 on 2025-12-04 02:42

import company.models.company
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0082_alter_companystaffnote_repeat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoperator',
            name='avatar_img',
            field=models.FileField(blank=True, null=True, upload_to=company.models.company.company_operator_directory_path, validators=[company.models.company.validate_file_size]),
        ),
        migrations.AddField(
            model_name='companyoperator',
            name='cccd_back_img',
            field=models.FileField(blank=True, null=True, upload_to=company.models.company.company_operator_directory_path, validators=[company.models.company.validate_file_size]),
        ),
        migrations.AddField(
            model_name='companyoperator',
            name='cccd_front_img',
            field=models.FileField(blank=True, null=True, upload_to=company.models.company.company_operator_directory_path, validators=[company.models.company.validate_file_size]),
        ),
    ]
