# Generated by Django 5.1.7 on 2026-05-22 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0083_companyoperator_avatar_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoperator',
            name='danglam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.operatorworkhistory'),
        ),
    ]
